# Generated by Django 3.0.6 on 2020-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='pinned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
