# Generated by Django 3.0.6 on 2020-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_channelmessage_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
