# Generated by Django 3.0.6 on 2020-05-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_channelmessage_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='ip_address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
