# Generated by Django 3.0.6 on 2020-05-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_channelmessage_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=2000)),
                ('moderate', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('blocked', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='channel_name',
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comments.Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.IPAddress'),
        ),
    ]
