# Generated by Django 3.0.6 on 2020-06-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_channelsession_channelviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelviewer',
            name='place',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
