# Generated by Django 3.0.6 on 2020-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_channelviewer_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsession',
            name='viewer',
        ),
        migrations.AddField(
            model_name='channelsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelsession',
            name='user_id',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelsession',
            name='user_name',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
